claimDailyReward: true
claimSeasonReward: true

rentCards: true

transferCardsToMainAccount: true

desiredLeague: 1

timers:
  executeTransfer: "00 18 * * *"
  checkStatus: "*/10 * * * *"

decLimit: 100.000

parallelExecution: 1
